let DavisModel = {
    outside_temperature:{
        current:"",
        high:"",
        high_time:"",
        lows_time:"",
        lows:""
    },
    inside_temperature:{
        current:"",
        high:"",
        high_time:"",
        lows_time:"",
        lows:""
    },
    outside_humidity:{
        current:"",
        high:"",
        high_time:"",
        lows_time:"",
        lows:""
    },
    inside_humidity:{
        current:"",
        high:"",
        high_time:"",
        lows_time:"",
        lows:""
    },
    barometer:{
        current:"",
        high:"",
        high_time:"",
        lows_time:"",
        lows:""
    },
    wind_speed:{
        current:"",
        high:"",
        high_time:""
    },
    rain:{
        rate:"",
        day:"",
        storm:"",
        month:"",
        year:""
    },
    last_hour_rain:{
        rate:""
    },
    soil_temperature_1:{
        current:"",
        high:"",
        high_time:"",
        lows_time:"",
        lows:""
    },
    soil_temperature_2:{
        current:"",
        high:"",
        high_time:"",
        lows_time:"",
        lows:""},
    soil_temperature_3:{
        current:"",
        high:"",
        high_time:"",
        lows_time:"",
        lows:""
    },
    soil_moisture_1:{
        current:"",
        high:"",
        high_time:"",
        lows_time:"",
        lows:""
    },
    soil_moisture_2:{
        current:"",
        high:"",
        high_time:"",
        lows_time:"",
        lows:""
    },
    soil_moisture_3:{
        current:"",
        high:"",
        high_time:"",
        lows_time:"",
        lows:""
    },
    createdAt:"",
    platformId: "",
    propertyId: ""
}

export default DavisModel